### ISSUE TITLE
How can I set transparency for each line/dot?

### ISSUE THREAD

**Issue by JackieAnxis** [lragnarsson/WebGL-BatchDraw#4]
WebGL-BatchDraw is an awesome work! And I'm working on it to visualize large networks. I met a problem. When I set the transparency of lines like that:
`batchDrawer.addLine(lines[i].fromX, lines[i].fromY, lines[i].toX, lines[i].toY, 0.5, 0, .5, 0, .1);`
However it produced the result as the right image below, and do you have any idea to set transparency of each line to produce the result like the left image below?
![image](https://user-images.githubusercontent.com/19246028/48816697-28bdf500-ed7e-11e8-9aee-45c496dda5c8.png)

**Comment by lragnarsson** [comment]
Cool that someone else is using this! I think this should be a fairly straight forward fix, give me a minute.

**Comment by lragnarsson** [comment]
@JackieAnxis  Could you try to checkout PR #5 and see if it gives you what you expect?
If it doesn't, you can play with changing the source and destination color blending factors (the lines I added in the main class) to any of these values:
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc

**Comment by JackieAnxis** [comment]
@lragnarsson Thanks! I solved this problem when I turned on the blend mode:
`gl.enable(gl.BLEND); gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);`

**Comment by JackieAnxis** [comment]
I'm going to draw some networks with your cool library, and here is a demo with a bitcoin trading network extracted from the trading log data in 01/01/2018, really cool.
![image](https://user-images.githubusercontent.com/19246028/48886316-7ada4580-ee66-11e8-8c72-e7341cb349be.png)

**Comment by lragnarsson** [comment]
Cool I updated to ONE, ONE_MINUS_SRC_ALPHA and merged the pull request into master.

The network looks really interesting, how many edges are there and what was the performance like?

**Comment by JackieAnxis** [comment]
The network upon contains more than 500k edges and it's very smooth to do the pan and zoom interactions on it. I think that your library will support more than 1m edges with the pan and zoom interactions without any mental interruption and I'm trying to build some tools based on your work to facilitate our researches, thanks a lot.

**Comment by lragnarsson** [comment]
Very nice to hear that! Good luck!
